#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRCTS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DOCR")]
	public partial class EmpDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EmpDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EmpConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOCR_Employee")]
		public int DOCR_Employee([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeID", DbType="VarChar(50)")] string employeeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeFirstName", DbType="VarChar(50)")] string employeeFirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeLastName", DbType="VarChar(50)")] string employeeLastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeEmail", DbType="VarChar(50)")] string employeeEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employeeID, employeeFirstName, employeeLastName, employeeEmail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOCR_getAllEmployee")]
		public ISingleResult<DOCR_getAllEmployeeResult> DOCR_getAllEmployee()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DOCR_getAllEmployeeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOCR_getEmployee")]
		public ISingleResult<DOCR_getEmployeeResult> DOCR_getEmployee([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<DOCR_getEmployeeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOCR_getEmployeeEM")]
		public ISingleResult<DOCR_getEmployeeEMResult> DOCR_getEmployeeEM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeEmail", DbType="VarChar(50)")] string employeeEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employeeEmail);
			return ((ISingleResult<DOCR_getEmployeeEMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOCR_UpdateEmployee")]
		public int DOCR_UpdateEmployee([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeID", DbType="VarChar(50)")] string employeeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeFirstName", DbType="VarChar(50)")] string employeeFirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeLastName", DbType="VarChar(50)")] string employeeLastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeEmail", DbType="VarChar(50)")] string employeeEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employeeID, employeeFirstName, employeeLastName, employeeEmail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOCR_EmployeeNA")]
		public int DOCR_EmployeeNA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeID", DbType="VarChar(50)")] string employeeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeFirstName", DbType="VarChar(50)")] string employeeFirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeLastName", DbType="VarChar(50)")] string employeeLastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeEmail", DbType="VarChar(50)")] string employeeEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employeeID, employeeFirstName, employeeLastName, employeeEmail);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee
	{
		
		private int _ID;
		
		private string _EmployeeID;
		
		private string _EmployeeFirstName;
		
		private string _EmployeeLastName;
		
		private string _EmployeeEmail;
		
		public Employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(50)")]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeFirstName", DbType="VarChar(50)")]
		public string EmployeeFirstName
		{
			get
			{
				return this._EmployeeFirstName;
			}
			set
			{
				if ((this._EmployeeFirstName != value))
				{
					this._EmployeeFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeLastName", DbType="VarChar(50)")]
		public string EmployeeLastName
		{
			get
			{
				return this._EmployeeLastName;
			}
			set
			{
				if ((this._EmployeeLastName != value))
				{
					this._EmployeeLastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeEmail", DbType="VarChar(50)")]
		public string EmployeeEmail
		{
			get
			{
				return this._EmployeeEmail;
			}
			set
			{
				if ((this._EmployeeEmail != value))
				{
					this._EmployeeEmail = value;
				}
			}
		}
	}
	
	public partial class DOCR_getAllEmployeeResult
	{
		
		private int _ID;
		
		private string _EmployeeID;
		
		private string _EmployeeFirstName;
		
		private string _EmployeeLastName;
		
		private string _EmployeeEmail;
		
		public DOCR_getAllEmployeeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(50)")]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeFirstName", DbType="VarChar(50)")]
		public string EmployeeFirstName
		{
			get
			{
				return this._EmployeeFirstName;
			}
			set
			{
				if ((this._EmployeeFirstName != value))
				{
					this._EmployeeFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeLastName", DbType="VarChar(50)")]
		public string EmployeeLastName
		{
			get
			{
				return this._EmployeeLastName;
			}
			set
			{
				if ((this._EmployeeLastName != value))
				{
					this._EmployeeLastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeEmail", DbType="VarChar(50)")]
		public string EmployeeEmail
		{
			get
			{
				return this._EmployeeEmail;
			}
			set
			{
				if ((this._EmployeeEmail != value))
				{
					this._EmployeeEmail = value;
				}
			}
		}
	}
	
	public partial class DOCR_getEmployeeResult
	{
		
		private int _ID;
		
		private string _EmployeeID;
		
		private string _EmployeeFirstName;
		
		private string _EmployeeLastName;
		
		private string _EmployeeEmail;
		
		public DOCR_getEmployeeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(50)")]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeFirstName", DbType="VarChar(50)")]
		public string EmployeeFirstName
		{
			get
			{
				return this._EmployeeFirstName;
			}
			set
			{
				if ((this._EmployeeFirstName != value))
				{
					this._EmployeeFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeLastName", DbType="VarChar(50)")]
		public string EmployeeLastName
		{
			get
			{
				return this._EmployeeLastName;
			}
			set
			{
				if ((this._EmployeeLastName != value))
				{
					this._EmployeeLastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeEmail", DbType="VarChar(50)")]
		public string EmployeeEmail
		{
			get
			{
				return this._EmployeeEmail;
			}
			set
			{
				if ((this._EmployeeEmail != value))
				{
					this._EmployeeEmail = value;
				}
			}
		}
	}
	
	public partial class DOCR_getEmployeeEMResult
	{
		
		private string _eid;
		
		public DOCR_getEmployeeEMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="NVarChar(50)")]
		public string eid
		{
			get
			{
				return this._eid;
			}
			set
			{
				if ((this._eid != value))
				{
					this._eid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
